/**
 * Generates supabase/seed.sql (content + demo data) from supabase/content/content.ts,
 * and supabase/setup.sql (all migrations + seed) for one-paste setup in the Supabase SQL editor.
 *
 *   npm run db:seed:generate
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { ACHIEVEMENTS, CHALLENGES, DEMO_LOGIN, DEMO_PLAYERS, LESSONS, PUZZLES, STORIES } from "../supabase/content/content";

const root = join(__dirname, "..");
const q = (s: string | null | undefined) => (s == null ? "null" : `'${s.replace(/'/g, "''")}'`);
const arr = (a: string[]) => (a.length ? `array[${a.map(q).join(", ")}]::text[]` : `'{}'::text[]`);
const json = (o: unknown) => `${q(JSON.stringify(o))}::jsonb`;
const levelForXp = (xp: number) => [0, 100, 250, 500, 900, 1400, 2000].filter((t) => xp >= t).length;

export function buildSeedSql(): string {
  const out: string[] = [];
  out.push("-- Generated by scripts/generate-seed.ts — edit supabase/content/content.ts instead.");
  out.push("begin;");

  out.push("\n-- Puzzles");
  PUZZLES.forEach((p, i) => {
    out.push(
      `insert into public.puzzles (slug, title, description, hint, fen, solution, difficulty, category, rating, is_mate, sort_order) values (${[
        q(p.slug), q(p.title), q(p.description), q(p.hint), q(p.fen), arr(p.solution), q(p.difficulty), q(p.category), p.rating, p.isMate, i + 1,
      ].join(", ")}) on conflict (slug) do update set title = excluded.title, description = excluded.description, hint = excluded.hint, fen = excluded.fen, solution = excluded.solution, difficulty = excluded.difficulty, category = excluded.category, rating = excluded.rating, is_mate = excluded.is_mate, sort_order = excluded.sort_order;`,
    );
  });

  out.push("\n-- Lessons");
  LESSONS.forEach((l, i) => {
    out.push(
      `insert into public.lessons (slug, title, category, description, content, difficulty, duration_minutes, order_index) values (${[
        q(l.slug), q(l.title), q(l.category), q(l.description), json(l.content), q(l.difficulty), l.durationMinutes, i + 1,
      ].join(", ")}) on conflict (slug) do update set title = excluded.title, category = excluded.category, description = excluded.description, content = excluded.content, difficulty = excluded.difficulty, duration_minutes = excluded.duration_minutes, order_index = excluded.order_index;`,
    );
  });

  out.push("\n-- Stories");
  STORIES.forEach((s, i) => {
    out.push(
      `insert into public.stories (slug, title, excerpt, content, category, symbol, read_minutes, source, published_at) values (${[
        q(s.slug), q(s.title), q(s.excerpt), q(s.paragraphs.join("\n\n")), q(s.category), q(s.symbol), s.readMinutes, q(s.source), `now() - interval '${STORIES.length - i} days'`,
      ].join(", ")}) on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, content = excluded.content, category = excluded.category, symbol = excluded.symbol, read_minutes = excluded.read_minutes, source = excluded.source;`,
    );
  });

  out.push("\n-- Challenges");
  CHALLENGES.forEach((c, i) => {
    out.push(
      `insert into public.challenges (slug, title, description, type, metric, period, target, reward_xp, href, sort_order) values (${[
        q(c.slug), q(c.title), q(c.description), q(c.type), q(c.metric), q(c.period), c.target, c.rewardXp, q(c.href), i + 1,
      ].join(", ")}) on conflict (slug) do update set title = excluded.title, description = excluded.description, type = excluded.type, metric = excluded.metric, period = excluded.period, target = excluded.target, reward_xp = excluded.reward_xp, href = excluded.href, sort_order = excluded.sort_order;`,
    );
  });

  out.push("\n-- Achievements");
  ACHIEVEMENTS.forEach((a, i) => {
    out.push(
      `insert into public.achievements (slug, name, description, icon, requirement, sort_order) values (${[
        q(a.slug), q(a.name), q(a.description), q(a.icon), json(a.requirement), i + 1,
      ].join(", ")}) on conflict (slug) do update set name = excluded.name, description = excluded.description, icon = excluded.icon, requirement = excluded.requirement, sort_order = excluded.sort_order;`,
    );
  });

  // Demo users: deterministic ids so the seed is idempotent.
  const demoUser = (n: number, email: string, password: string | null, meta: Record<string, string>) => {
    const id = `d0000000-0000-4000-8000-${String(n).padStart(12, "0")}`;
    const pw = password ? `extensions.crypt(${q(password)}, extensions.gen_salt('bf'))` : `extensions.crypt(gen_random_uuid()::text, extensions.gen_salt('bf'))`;
    return [
      `insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, email_change, email_change_token_new, recovery_token)
values ('00000000-0000-0000-0000-000000000000', '${id}', 'authenticated', 'authenticated', ${q(email)}, ${pw}, now(), '{"provider":"email","providers":["email"]}'::jsonb, ${json(meta)}, now() - interval '60 days', now(), '', '', '', '')
on conflict (id) do nothing;`,
      `insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values ('${id}', '${id}', '${id}', ${json({ sub: id, email, email_verified: true })}, 'email', now(), now(), now())
on conflict do nothing;`,
      id,
    ] as const;
  };

  out.push("\n-- Demo leaderboard players (cannot log in: random passwords)");
  DEMO_PLAYERS.forEach((p, i) => {
    const [u, ident, id] = demoUser(i + 1, `${p.username.replace(/\./g, "-")}@demo.sankofachess.app`, null, {
      username: p.username, display_name: p.displayName, country: p.country, chess_level: "intermediate",
    });
    const wins = Math.round(p.games * 0.52);
    const draws = Math.round(p.games * 0.08);
    out.push(u, ident);
    out.push(
      `update public.profiles set is_demo = true, onboarded_at = now(), rating = ${p.rating}, peak_rating = ${p.rating + 25}, xp = ${p.xp}, sankofa_level = ${levelForXp(p.xp)}, games_played = ${p.games}, wins = ${wins}, draws = ${draws}, losses = ${p.games - wins - draws}, streak = ${(i * 3) % 11}, best_streak = ${10 + (i % 9)} where id = '${id}';`,
    );
  });

  out.push("\n-- Demo login account (for local development and previews — remove before public launch)");
  const [u, ident, id] = demoUser(999, DEMO_LOGIN.email, DEMO_LOGIN.password, {
    username: DEMO_LOGIN.username, display_name: DEMO_LOGIN.displayName, country: DEMO_LOGIN.country, chess_level: "intermediate",
  });
  out.push(u, ident);
  out.push(`update public.profiles set is_demo = true, onboarded_at = now(), goal = 'tactics', timezone = 'Europe/Brussels' where id = '${id}';`);

  out.push("\ncommit;");
  return out.join("\n") + "\n";
}

function main() {
  const seed = buildSeedSql();
  writeFileSync(join(root, "supabase", "seed.sql"), seed);
  const migDir = join(root, "supabase", "migrations");
  const migrations = readdirSync(migDir)
    .filter((f) => f.endsWith(".sql"))
    .sort()
    .map((f) => `-- ===== ${f} =====\n` + readFileSync(join(migDir, f), "utf8"));
  writeFileSync(
    join(root, "supabase", "setup.sql"),
    `-- Sankofa Chess: one-paste setup for a NEW Supabase project (SQL Editor → New query → Run).\n-- Contains every migration followed by the seed data. Generated — do not edit by hand.\n\n${migrations.join("\n\n")}\n\n-- ===== seed =====\n${seed}`,
  );
  console.log(`seed.sql and setup.sql written (${PUZZLES.length} puzzles, ${LESSONS.length} lessons, ${STORIES.length} stories).`);
}

if (typeof require !== "undefined" && require.main === module) main();
